---
title: "RNA-seq_Coverage"
author: "John D."
date: "June 13, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Comparing mapping quality of assemblies and reference
```{r}
library(tidyverse)
library(reshape2)

Ref <- read.table("Reference_Star_Stats.tab", header = T) %>%
  mutate(Assembly = "Reference")

D1 <- read.table("Davis_1_pseudohap_Star_Stats.tab", header = T) %>%
  mutate(Assembly = "Davis_1") %>%
  filter(Sample %in% Ref$Sample)

D2 <- read.table("Davis_2_pseudohap_Star_Stats.tab", header = T) %>%
  mutate(Assembly = "Davis_2") %>%
  filter(Sample %in% Ref$Sample)

N1 <- read.table("Novogene_1_pseudohap_Star_Stats.tab", header = T) %>%
  mutate(Assembly = "Novogene_1") %>%
  filter(Sample %in% Ref$Sample)

N2 <- read.table("Novogene_2_pseudohap_Star_Stats.tab", header = T) %>%
  mutate(Assembly = "Novogene_2") %>%
  filter(Sample %in% Ref$Sample)

All <- rbind(Ref,D1,D2,N1,N2)

All$Percent_Combined_Unmapped <- 100 - All$Percent_Unique_Mapped - All$Percent_Multi_Mapped

All %>%
  ggplot(aes(Assembly,Percent_Unique_Mapped, fill = Assembly)) +
  geom_bar(stat = "identity") +
  facet_wrap(~Sample, nrow = 2) +
  geom_text(aes(label = Percent_Unique_Mapped), nudge_y = 2.5) +
  ggtitle("Percent Unique Mapped") +
   theme(axis.text.x=element_text(angle=90, hjust=1), plot.title = element_text(hjust = 0.5))

All %>%
  ggplot(aes(Assembly,Percent_Multi_Mapped, fill = Assembly)) +
  geom_bar(stat = "identity") +
  facet_wrap(~Sample, nrow = 2) +
  geom_text(aes(label = Percent_Multi_Mapped), nudge_y = 2.5) +
  ggtitle("Percent Multi Mapped") +
   theme(axis.text.x=element_text(angle=90, hjust=1), plot.title = element_text(hjust = 0.5))

All %>%
  ggplot(aes(Assembly,Percent_Combined_Unmapped, fill = Assembly)) +
  geom_bar(stat = "identity") +
  facet_wrap(~Sample, nrow = 2) +
  geom_text(aes(label = Percent_Combined_Unmapped), nudge_y = 2.5) +
  ggtitle("Percent Unmapped") +
   theme(axis.text.x=element_text(angle=90, hjust=1), plot.title = element_text(hjust = 0.5))

m.All <- All %>%
  select(Assembly,Sample,Percent_Unique_Mapped,Percent_Multi_Mapped,Percent_Combined_Unmapped) %>%
  melt(id.vars = c("Assembly","Sample")) %>%
  rename(Mapping = variable, Percent = value)

m.All %>%
  ggplot(aes(Assembly,Percent, fill = factor(Mapping, labels= c("Unique", "Multi","Unmapped")))) +
  geom_bar(stat = "identity") +
  facet_wrap(~Sample, nrow = 2) +
  ggtitle("Overall Mapping") +
  theme(axis.text.x=element_text(angle=90, hjust=1), plot.title = element_text(hjust = 0.5)) + 
  scale_fill_discrete(name = "Mapping")
```

